type TaskData = {
  taskId: string;
  course: string;
  title: string;
  dateStarted: string;
  score: string;
  details: string;
  status: TaskStatuses;
  imageUrl: string;
  answer: string;
};

export enum TaskStatuses {
  PROGRESS = "in_progress",
  COMPLETED = "completed",
  REJECTED = "rejected",
}

export const tasksData: TaskData[] = [
  {
    taskId: '#20462',
    course: 'Course1',
    title: 'Build an application',
    dateStarted: '2022-05-13 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#18933',
    course: 'Course2',
    title: 'Build an application',
    dateStarted: '2022-05-22 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#45169',
    course: 'Course3',
    title: 'Build an application',
    dateStarted: '2022-06-15 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'in_progress',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#34304',
    course: 'Course4',
    title: 'Build an application',
    dateStarted: '2022-09-06 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'in_progress',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#17188',
    course: 'Course5',
    title: 'Build an application',
    dateStarted: '2022-09-22 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'rejected',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#73003',
    course: 'Course6',
    title: 'Build an application',
    dateStarted: '2022-10-04 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#58825',
    course: 'Course7',
    title: 'Build an application',
    dateStarted: '2022-10-17 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#44122',
    course: 'Course8',
    title: 'Build an application',
    dateStarted: '2022-10-24 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#37291',
    course: 'Course9',
    title: 'Build an application',
    dateStarted: '2022-11-05 00:00:00+00:00',
    score: '7/10',
    details: 'This task contains... ',
    status: 'in_progress',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#42377',
    course: 'Course10',
    title: 'Build an application',
    dateStarted: '2022-11-08 00:00:00+00:00',
    score: '8/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#53891',
    course: 'Course11',
    title: 'Build an application',
    dateStarted: '2022-11-12 00:00:00+00:00',
    score: '7/10',
    details: 'This task contains... ',
    status: 'in_progress',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#62145',
    course: 'Course12',
    title: 'Build an application',
    dateStarted: '2022-11-18 00:00:00+00:00',
    score: '9/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#76354',
    course: 'Course13',
    title: 'Build an application',
    dateStarted: '2022-11-22 00:00:00+00:00',
    score: '7/10',
    details: 'This task contains... ',
    status: 'in_progress',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#89237',
    course: 'Course14',
    title: 'Build an application',
    dateStarted: '2022-11-26 00:00:00+00:00',
    score: '8/10',
    details: 'This task contains... ',
    status: 'rejected',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#92362',
    course: 'Course15',
    title: 'Build an application',
    dateStarted: '2022-11-30 00:00:00+00:00',
    score: '6/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#104583',
    course: 'Course16',
    title: 'Build an application',
    dateStarted: '2022-12-03 00:00:00+00:00',
    score: '7/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#115676',
    course: 'Course17',
    title: 'Build an application',
    dateStarted: '2022-12-07 00:00:00+00:00',
    score: '9/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#126897',
    course: 'Course18',
    title: 'Build an application',
    dateStarted: '2022-12-11 00:00:00+00:00',
    score: '8/10',
    details: 'This task contains... ',
    status: 'in_progress',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#138932',
    course: 'Course19',
    title: 'Build an application',
    dateStarted: '2022-12-15 00:00:00+00:00',
    score: '7/10',
    details: 'This task contains... ',
    status: 'completed',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
  {
    taskId: '#149683',
    course: 'Course20',
    title: 'Build an application',
    dateStarted: '2022-12-18 00:00:00+00:00',
    score: '9/10',
    details: 'This task contains... ',
    status: 'rejected',
    imageUrl: 'https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg',
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Nulla vitae massa. Cras sollicitudin. Nunc purus. Fusce consectetuer risus et tortor. Donec vitae orci sed dolor rutrum auctor. Integer id quam. Morbi mi. Pellentesque ut neque. Nam elit agna, vehicula euismod eu, pellentesque ac dui.",
  },
] as unknown as TaskData[];